import bplStats from '../data/bplStats.json';

/**
 * Search BPL static data by player name.
 *
 * Handles two JSON formats transparently:
 *
 * NEW (leaderboard format, generated by stats-generator):
 *   { competition, lastUpdated, data: [{ tournamentName, tournamentId, batting: [], bowling: [] }] }
 *
 * OLD (player-profile format, legacy):
 *   { tournament, players: [{ player_id, name, teams, batting: {}, bowling: {} }] }
 *
 * @param {string} query  Partial or full player name, case-insensitive.
 * @returns {object[]}    Matching player records.
 */
export function searchBPLStats(query) {
  if (!query || query.trim().length < 2) return [];
  const words = query.trim().toLowerCase().split(/\s+/);

  // ── NEW leaderboard format ───────────────────────────────────────────────────
  if (Array.isArray(bplStats.data)) {
    const results = [];
    for (const tournament of bplStats.data) {
      for (const battingRecord of tournament.batting || []) {
        const name = battingRecord.player?.toLowerCase() || '';
        if (!words.every(w => name.includes(w))) continue;

        const bowlingRecord = (tournament.bowling || []).find(
          b => b.player === battingRecord.player && b.team === battingRecord.team
        ) || null;

        results.push({
          id: `bpl-${tournament.tournamentId}-${battingRecord.rank}`,
          name: battingRecord.player,
          team: battingRecord.team,
          source: 'bpl-static',
          tournament: tournament.tournamentName,
          lastUpdated: bplStats.lastUpdated,
          batting: battingRecord,
          bowling: bowlingRecord,
        });
      }
    }
    return results;
  }

  // ── OLD player-profile format (fallback) ─────────────────────────────────────
  if (Array.isArray(bplStats.players)) {
    return bplStats.players
      .filter(p => {
        const name = p.name?.toLowerCase() || '';
        return words.every(w => name.includes(w));
      })
      .map(p => ({
        id: `bpl-${p.player_id}`,
        name: p.name,
        team: p.teams?.[0]?.team_name || 'Unknown',
        source: 'bpl-static',
        tournament: bplStats.tournament || 'BPL',
        lastUpdated: '4th June 2026',
        // Remap old field names to new so BPLPlayerCard renders correctly
        batting: p.batting ? {
          inns:     p.batting.innings,
          mat:      p.batting.matches,
          runs:     p.batting.runs,
          avg:      p.batting.average,
          sr:       p.batting.strike_rate,
          highest:  p.batting.highest_score,
          no:       p.batting.not_outs,
          balls:    p.batting.balls_faced,
          hand:     p.batting.batting_hand,
          fours:    p.batting.fours,
          sixes:    p.batting.sixes,
          fifties:  p.batting.fifties,
          hundreds: p.batting.hundreds,
          rank:     null,
        } : null,
        bowling: p.bowling ? {
          inns:     p.bowling.innings,
          mat:      p.bowling.matches,
          wickets:  p.bowling.wickets,
          overs:    p.bowling.overs,
          runs:     p.bowling.runs_conceded,
          econ:     p.bowling.economy,
          avg:      p.bowling.average,
          highest:  p.bowling.best_wickets,
          maidens:  p.bowling.maidens,
          style:    p.bowling.bowling_style,
          rank:     null,
        } : null,
      }));
  }

  return [];
}
