'use strict';

/**
 * @module battingAggregationService
 * @description Loads YPL static batting JSON files and provides consolidation logic.
 *
 * File layout (relative to cricsearch-backend/):
 *   data/sportygo/ypl/batting/{year}/team-{teamId}.json   ← live import output
 *   data/sportygo/ypl/batting/{year}/consolidated.json     ← generated by import script
 *   data/sportygo/ypl/batting/{year}/sample-team-{teamId}.json  ← bundled fallback
 *   data/sportygo/ypl/batting/{year}/sample-consolidated.json   ← bundled fallback
 */

const fs   = require('fs');
const path = require('path');
const { calcAverage, calcStrikeRate, parseHighestScore } = require('../utils/parseCricketStats');

const DATA_ROOT = path.join(__dirname, '../../data/sportygo/ypl/batting');

// ── File helpers ─────────────────────────────────────────────────────────────

function teamFile(year, teamId, sample = false) {
  const name = sample ? `sample-team-${teamId}.json` : `team-${teamId}.json`;
  return path.join(DATA_ROOT, String(year), name);
}

function consolidatedFile(year, sample = false) {
  const name = sample ? 'sample-consolidated.json' : 'consolidated.json';
  return path.join(DATA_ROOT, String(year), name);
}

function readJsonFile(filePath) {
  if (!fs.existsSync(filePath)) return null;
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  } catch {
    return null;
  }
}

/**
 * Load a team file, falling back to sample data if the live file doesn't exist.
 * Returns null when neither file exists.
 *
 * @param {string} year
 * @param {string} teamId
 * @returns {{ data: object|null, usingSample: boolean }}
 */
function loadTeamData(year, teamId) {
  const live = readJsonFile(teamFile(year, teamId, false));
  if (live) return { data: live, usingSample: false };

  const sample = readJsonFile(teamFile(year, teamId, true));
  if (sample) return { data: sample, usingSample: true };

  return { data: null, usingSample: false };
}

/**
 * Load consolidated data, falling back to sample.
 */
function loadConsolidatedData(year) {
  const live = readJsonFile(consolidatedFile(year, false));
  if (live) return { data: live, usingSample: false };

  const sample = readJsonFile(consolidatedFile(year, true));
  if (sample) return { data: sample, usingSample: true };

  return { data: null, usingSample: false };
}

/**
 * List years that have data available (live or sample).
 * @returns {string[]} sorted descending
 */
function listAvailableYears() {
  if (!fs.existsSync(DATA_ROOT)) return [];
  const dirs = fs.readdirSync(DATA_ROOT, { withFileTypes: true })
    .filter((d) => d.isDirectory() && /^\d{4}$/.test(d.name))
    .map((d) => d.name);
  return dirs.sort((a, b) => Number(b) - Number(a));
}

// ── Consolidation logic ───────────────────────────────────────────────────────

/**
 * Merge two player records (same player name, different teams).
 * Sums countable stats, recalculates average and strike rate, takes max HS.
 */
function mergePlayers(a, b) {
  const mat        = (a.matches    || 0) + (b.matches    || 0);
  const inn        = (a.innings    || 0) + (b.innings    || 0);
  const no         = (a.notOuts    || 0) + (b.notOuts    || 0);
  const runs       = (a.runs       || 0) + (b.runs       || 0);
  const bf         = (a.ballsFaced || 0) + (b.ballsFaced || 0);
  const hundreds   = (a.hundreds   || 0) + (b.hundreds   || 0);
  const fifties    = (a.fifties    || 0) + (b.fifties    || 0);
  const fours      = (a.fours      || 0) + (b.fours      || 0);
  const sixes      = (a.sixes      || 0) + (b.sixes      || 0);
  const ducks      = (a.ducks      || 0) + (b.ducks      || 0);

  // Pick highest score (preserve not-out symbol for the winner)
  const aHS = parseHighestScore(a.highestScore);
  const bHS = parseHighestScore(b.highestScore);
  let hs, hsNumeric;
  if ((aHS.numeric || 0) >= (bHS.numeric || 0)) {
    hs = a.highestScore; hsNumeric = aHS.numeric;
  } else {
    hs = b.highestScore; hsNumeric = bHS.numeric;
  }

  return {
    sourceName:          a.sourceName,
    clubId:              a.clubId,
    teamId:              'consolidated',
    year:                a.year || b.year,
    playerName:          a.playerName,
    matches:             mat,
    innings:             inn,
    notOuts:             no,
    runs,
    highestScore:        hs || '-',
    highestScoreNumeric: hsNumeric,
    average:             calcAverage(runs, inn, no),
    ballsFaced:          bf || null,
    strikeRate:          calcStrikeRate(runs, bf),
    hundreds,
    fifties,
    fours,
    sixes,
    ducks,
    teams:               [...(a.teams || [a.teamId]), b.teamId].filter(Boolean),
  };
}

/**
 * Consolidate players from multiple team datasets.
 * Players with matching names (case-insensitive) across teams are merged.
 *
 * @param {object[][]} teamPlayerArrays  One array of players per team
 * @returns {object[]}  Merged player list sorted by runs desc
 */
function consolidatePlayers(teamPlayerArrays) {
  const map = new Map(); // normalised name → merged record

  teamPlayerArrays.flat().forEach((player) => {
    const key = (player.playerName || '').toLowerCase().trim();
    if (!key) return;

    if (map.has(key)) {
      map.set(key, mergePlayers(map.get(key), player));
    } else {
      map.set(key, { ...player, teams: [player.teamId] });
    }
  });

  return Array.from(map.values())
    .sort((a, b) => (b.runs || 0) - (a.runs || 0));
}

/**
 * Build and return a consolidated data envelope from team data files for a given year.
 * Used by the import script to write consolidated.json.
 *
 * @param {string} year
 * @param {string[]} teamIds
 * @returns {{ consolidated: object, usingSample: boolean }}
 */
function buildConsolidated(year, teamIds = ['211', '120']) {
  const teamDatasets = [];
  let usingSample = false;

  teamIds.forEach((tid) => {
    const { data, usingSample: s } = loadTeamData(year, tid);
    if (data && Array.isArray(data.players)) {
      teamDatasets.push(data.players);
      if (s) usingSample = true;
    }
  });

  const players = consolidatePlayers(teamDatasets);

  return {
    consolidated: {
      source:      'sportygo-ypl',
      displayName: 'YPL',
      clubId:      process.env.SPORTYGO_CLUB_ID || '4263',
      teamId:      'consolidated',
      year:        String(year),
      sourceUrl:   null,
      importedAt:  new Date().toISOString(),
      isSample:    usingSample,
      players,
    },
    usingSample,
  };
}

module.exports = {
  loadTeamData,
  loadConsolidatedData,
  listAvailableYears,
  consolidatePlayers,
  buildConsolidated,
  DATA_ROOT,
  teamFile,
  consolidatedFile,
};
